package br.com.start.model;

public enum AreaDeConhecimento {
	
	CIENCIA_EXTAS_E_DA_TERRA,
	CIENCIAS_BIOLOGICAS,
	ENGENHARIAS,
	CIENCIAS_DA_SAUDE,
	CIENCIAS_SOCIAIS_APLICADAS,
	CIENCIAS_HUMANAS,
	LINGUISTICA_LETRAS_E_ARTES
	
	

}
